export const DIRECTOR_ALL_PENDING = 'DIRECTOR_ALL_PENDING';
export const DIRECTOR_ALL_FULFILLED = 'DIRECTOR_ALL_FULFILLED';
export const DIRECTOR_ALL_REJECTED = 'DIRECTOR_ALL_REJECTED';

export const DIRECTOR_GET_PENDING = 'DIRECTOR_GET_PENDING';
export const DIRECTOR_GET_FULFILLED = 'DIRECTOR_GET_FULFILLED';
export const DIRECTOR_GET_REJECTED = 'DIRECTOR_GET_REJECTED';

export const DIRECTOR_PUT_PENDING = 'DIRECTOR_PUT_PENDING';
export const DIRECTOR_PUT_FULFILLED = 'DIRECTOR_PUT_FULFILLED';
export const DIRECTOR_PUT_REJECTED = 'DIRECTOR_PUT_REJECTED';

export const DIRECTOR_POST_PENDING = 'DIRECTOR_POST_PENDING';
export const DIRECTOR_POST_FULFILLED = 'DIRECTOR_POST_FULFILLED';
export const DIRECTOR_POST_REJECTED = 'DIRECTOR_POST_REJECTED';

export const DIRECTOR_DELETE_PENDING = 'DIRECTOR_DELETE_PENDING';
export const DIRECTOR_DELETE_FULFILLED = 'DIRECTOR_DELETE_FULFILLED';
export const DIRECTOR_DELETE_REJECTED = 'DIRECTOR_DELETE_REJECTED';