export const CATEGORY_PENDING = 'CATEGORY_PENDING';
export const CATEGORY_FULFILLED = 'CATEGORY_FULFILLED';
export const CATEGORY_REJECTED = 'CATEGORY_REJECTED';

export const CATEGORY_GET_PENDING = 'CATEGORY_GET_PENDING';
export const CATEGORY_GET_FULFILLED = 'CATEGORY_GET_FULFILLED';
export const CATEGORY_GET_REJECTED = 'CATEGORY_GET_REJECTED';

export const CATEGORY_POST_PENDING = 'CATEGORY_POST_PENDING';
export const CATEGORY_POST_FULFILLED = 'CATEGORY_POST_FULFILLED';
export const CATEGORY_POST_REJECTED = 'CATEGORY_POST_REJECTED';

export const CATEGORY_PUT_PENDING = 'CATEGORY_PUT_PENDING';
export const CATEGORY_PUT_FULFILLED = 'CATEGORY_PUT_FULFILLED';
export const CATEGORY_PUT_REJECTED = 'CATEGORY_PUT_REJECTED';

export const CATEGORY_DELETE_PENDING = 'CATEGORY_DELETE_PENDING';
export const CATEGORY_DELETE_FULFILLED = 'CATEGORY_DELETE_FULFILLED';
export const CATEGORY_DELETE_REJECTED = 'CATEGORY_DELETE_REJECTED';