export const MOVIES_ALL_PENDING = 'MOVIES_ALL_PENDING';
export const MOVIES_ALL_FULFILLED = 'MOVIES_ALL_FULFILLED';
export const MOVIES_ALL_REJECTED = 'MOVIES_ALL_REJECTED';

export const MOVIES_GET_PENDING = 'MOVIES_GET_PENDING';
export const MOVIES_GET_FULFILLED = 'MOVIES_GET_FULFILLED';
export const MOVIES_GET_REJECTED = 'MOVIES_GET_REJECTED';

export const MOVIES_POST_PENDING = 'MOVIES_POST_PENDING';
export const MOVIES_POST_FULFILLED = 'MOVIES_POST_FULFILLED';
export const MOVIES_POST_REJECTED = 'MOVIES_POST_REJECTED';

export const MOVIES_DELETE_PENDING = 'MOVIES_DELETE_PENDING';
export const MOVIES_DELETE_FULFILLED = 'MOVIES_DELETE_FULFILLED';
export const MOVIES_DELETE_REJECTED = 'MOVIES_DELETE_REJECTED';

export const MOVIES_PUT_PENDING = 'MOVIES_PUT_PENDING';
export const MOVIES_PUT_FULFILLED = 'MOVIES_PUT_FULFILLED';
export const MOVIES_PUT_REJECTED = 'MOVIES_PUT_REJECTED';
